// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheWeebDenShop.Data;

#nullable disable

namespace TheWeebDenShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheWeebDenShop.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TheWeebDenShop.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Short")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Volumes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "p1",
                            Author = "Koyoharu Gotouge",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8487),
                            Description = "Complete 23-volume Demon Slayer manga box set with premium storage case. Follow Tanjiro's entire journey from beginning to end.",
                            Genre = "Action",
                            Image = "products/images/demon-slayer.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Demon Slayer Box Set (Vol.1–23)",
                            Price = 10640m,
                            Rating = 4.7999999999999998,
                            Short = "Kimetsu no Yaiba complete manga box set",
                            Stock = 12,
                            Volumes = 23
                        },
                        new
                        {
                            Id = "p2",
                            Author = "Gege Akutami",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8495),
                            Description = "Yuji Itadori swallows Sukuna's finger and begins his chaotic days at Tokyo Jujutsu High School.",
                            Genre = "Action",
                            Image = "products/images/jujutsu-kaisen.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Jujutsu Kaisen Vol. 1",
                            Price = 503m,
                            Rating = 4.5999999999999996,
                            Short = "Yuji Itadori begins his journey",
                            Stock = 34,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p3",
                            Author = "Tatsuki Fujimoto",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8498),
                            Description = "Denji and Pochita's strange partnership. A bloody yet heartbreaking story collected in Part 1 box set.",
                            Genre = "Action",
                            Image = "products/images/chainsaw-man.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Chainsaw Man Box Set (Vol.1–11)",
                            Price = 4479m,
                            Rating = 4.7000000000000002,
                            Short = "Chainsaw Man Part 1 box set",
                            Stock = 0,
                            Volumes = 11
                        },
                        new
                        {
                            Id = "p4",
                            Author = "Hajime Isayama",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8499),
                            Description = "When titans breach Wall Maria, Eren Yeager witnesses unimaginable horror and vows revenge against the titans.",
                            Genre = "Action",
                            Image = "products/images/attack-on-titan.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Attack on Titan Vol. 1",
                            Price = 559m,
                            Rating = 4.9000000000000004,
                            Short = "Humanity's fight for survival begins",
                            Stock = 7,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p5",
                            Author = "Kohei Horikoshi",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8501),
                            Description = "Izuku Midoriya dreams of becoming a hero despite being born without a Quirk in a world where superpowers are common.",
                            Genre = "Action",
                            Image = "products/images/my-hero-academia.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "My Hero Academia Vol. 1",
                            Price = 503m,
                            Rating = 4.5,
                            Short = "Izuku's journey to become a hero",
                            Stock = 30,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p6",
                            Author = "Eiichiro Oda",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8503),
                            Description = "Monkey D. Luffy sets out to sea to find the legendary treasure One Piece and become the next Pirate King.",
                            Genre = "Adventure",
                            Image = "products/images/one-piece.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "One Piece Vol. 1",
                            Price = 559m,
                            Rating = 4.7999999999999998,
                            Short = "Luffy begins his pirate adventure",
                            Stock = 40,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p7",
                            Author = "Masashi Kishimoto",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8504),
                            Description = "Follow Naruto Uzumaki from his academy days through the Chunin Exams in this comprehensive box set.",
                            Genre = "Action",
                            Image = "products/images/naruto.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Naruto Box Set 1 (Vol.1–27)",
                            Price = 8959m,
                            Rating = 4.7000000000000002,
                            Short = "First Naruto box set collection",
                            Stock = 15,
                            Volumes = 27
                        },
                        new
                        {
                            Id = "p8",
                            Author = "Sui Ishida",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8506),
                            Description = "College student Ken Kaneki's life changes forever when he encounters a ghoul and becomes a half-ghoul himself.",
                            Genre = "Horror",
                            Image = "products/images/tokyo-ghoul.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Tokyo Ghoul Vol. 1",
                            Price = 503m,
                            Rating = 4.4000000000000004,
                            Short = "Ken Kaneki's transformation begins",
                            Stock = 0,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p9",
                            Author = "Tsugumi Ohba",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8535),
                            Description = "The complete Death Note series featuring Light Yagami's psychological battle with the detective L.",
                            Genre = "Thriller",
                            Image = "products/images/death-note.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Death Note Box Set",
                            Price = 3079m,
                            Rating = 4.9000000000000004,
                            Short = "Complete Death Note collection",
                            Stock = 18,
                            Volumes = 12
                        },
                        new
                        {
                            Id = "p10",
                            Author = "Hiromu Arakawa",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8537),
                            Description = "Edward and Alphonse Elric attempt to use alchemy to bring their mother back to life with devastating consequences.",
                            Genre = "Fantasy",
                            Image = "products/images/fullmetal-alchemist.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Fullmetal Alchemist Vol. 1",
                            Price = 559m,
                            Rating = 4.7999999999999998,
                            Short = "The Elric brothers' alchemical journey",
                            Stock = 22,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p11",
                            Author = "Makoto Shinkai",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8539),
                            Description = "The original light novel that inspired the beloved anime film about two teenagers who mysteriously swap bodies.",
                            Genre = "Romance",
                            Image = "products/images/your-name.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Your Name Light Novel",
                            Price = 727m,
                            Rating = 4.5999999999999996,
                            Short = "The story behind the hit anime film",
                            Stock = 35,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p12",
                            Author = "Hayao Miyazaki",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8540),
                            Description = "A beautifully illustrated picture book adaptation of Hayao Miyazaki's Academy Award-winning film.",
                            Genre = "Fantasy",
                            Image = "products/images/spirited-away.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Spirited Away Picture Book",
                            Price = 1119m,
                            Rating = 4.7000000000000002,
                            Short = "Studio Ghibli's masterpiece in book form",
                            Stock = 5,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p13",
                            Author = "Fujino Omori & Toshi Aoi",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8542),
                            Description = "Will Serfort enrolls in a prestigious magic academy despite being unable to use magic, relying solely on his sword skills to prove himself among talented mages.",
                            Genre = "Action",
                            Image = "products/images/wistoria.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Wistoria: Wand and Sword Season 1 Blu-ray",
                            Price = 2799m,
                            Rating = 4.5,
                            Short = "Magic academy action anime complete season",
                            Stock = 25,
                            Volumes = 1
                        },
                        new
                        {
                            Id = "p14",
                            Author = "Kei Urana",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8543),
                            Description = "Follow Rudo as he's exiled to the trash-filled abyss and discovers mysterious powers. Complete volumes 1-6 from Kei Urana's acclaimed dark fantasy series.",
                            Genre = "Action",
                            Image = "products/images/gachiakuta.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Gachiakuta Vol. 1-6 Collection",
                            Price = 3919m,
                            Rating = 4.7000000000000002,
                            Short = "Post-apocalyptic action manga bundle",
                            Stock = 18,
                            Volumes = 6
                        },
                        new
                        {
                            Id = "p15",
                            Author = "Yukinobu Tatsu",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8545),
                            Description = "Momo and Okarun's wild adventures battling aliens and spirits. Deluxe box set featuring volumes 1-8 of Yukinobu Tatsu's hit supernatural action-comedy manga.",
                            Genre = "Action",
                            Image = "products/images/dandandan.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "DanDaDan Vol. 1-8 Ultimate Box Set",
                            Price = 5039m,
                            Rating = 4.7999999999999998,
                            Short = "Aliens, ghosts, and supernatural chaos",
                            Stock = 14,
                            Volumes = 8
                        },
                        new
                        {
                            Id = "p16",
                            Author = "Ken Wakui",
                            CreatedAt = new DateTime(2026, 3, 5, 9, 59, 31, 155, DateTimeKind.Utc).AddTicks(8546),
                            Description = "Takemichi Hanagaki travels back in time to save his ex-girlfriend from a tragic fate. First two volumes of Ken Wakui's thrilling time-leap gang story.",
                            Genre = "Action",
                            Image = "products/images/tokyorevengers.jpg",
                            IsApproved = true,
                            IsBanned = false,
                            Name = "Tokyo Revengers Vol. 1-2",
                            Price = 1119m,
                            Rating = 4.5999999999999996,
                            Short = "Time-traveling delinquent action",
                            Stock = 32,
                            Volumes = 2
                        });
                });

            modelBuilder.Entity("TheWeebDenShop.Models.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerPath")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheWeebDenShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheWeebDenShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheWeebDenShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheWeebDenShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheWeebDenShop.Models.Product", b =>
                {
                    b.HasOne("TheWeebDenShop.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Store");
                });

            modelBuilder.Entity("TheWeebDenShop.Models.Store", b =>
                {
                    b.HasOne("TheWeebDenShop.Models.ApplicationUser", "Owner")
                        .WithOne("Store")
                        .HasForeignKey("TheWeebDenShop.Models.Store", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TheWeebDenShop.Models.ApplicationUser", b =>
                {
                    b.Navigation("Store");
                });

            modelBuilder.Entity("TheWeebDenShop.Models.Store", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
